name: indowater_mobile
description: IndoWater Prepaid Water Meter Management System Mobile App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# Alternatively, dependencies can be manually updated by changing the version numbers below.
# For more information, see: https://dart.dev/get-dependencies/dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  
  # State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  
  # Networking
  dio: ^5.3.0
  http: ^1.1.0
  connectivity_plus: ^4.0.1
  
  # Local Storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  
  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.5.0
  flutter_spinkit: ^5.2.0
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4
  
  # Charts and Graphs
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^22.2.7
  
  # Authentication
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.1.12
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.2
  permission_handler: ^10.4.3
  image_picker: ^1.0.1
  file_picker: ^5.3.2
  path: ^1.8.3
  uuid: ^3.0.7
  
  # Notifications
  flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  
  # Payment Gateways
  midtrans_sdk: ^0.3.4
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.3.0
  
  # Location
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  
  # Animations
  flutter_animate: ^4.2.0
  
  # Responsive UI
  responsive_framework: ^1.1.0
  
  # Form Validation
  form_field_validator: ^1.1.0
  
  # Internationalization
  easy_localization: ^3.0.2
  
  # Logging
  logger: ^1.4.0
  
  # Dependency Injection
  get_it: ^7.6.0
  
  # Testing
  mockito: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^2.0.2
  
  # Build
  build_runner: ^2.4.6
  
  # Testing
  bloc_test: ^9.1.3
  
  # Icons
  flutter_launcher_icons: ^0.13.1
  
  # Native Splash Screen
  flutter_native_splash: ^2.3.1

# Flutter Launcher Icons configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash.png"
  color_dark: "#121212"
  image_dark: "assets/images/splash_dark.png"
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages