global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Ling Industri API monitoring
  - job_name: 'lingindustri-api'
    static_configs:
      - targets: ['api:80']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Ling Industri Frontend monitoring
  - job_name: 'lingindustri-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Database monitoring
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
    scrape_interval: 30s

  # System monitoring
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Custom monitoring dashboard
  - job_name: 'monitoring-dashboard'
    static_configs:
      - targets: ['monitoring-dashboard:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s